### ISSUE TITLE
Busting cloudfront cache when serving from a bucket

### ISSUE THREAD

**Issue by pessoa** [Kixeye/untar-to-s3#2]
untar-to-s3 has been working great for my use case untar to one bucket that I use to feed cloudfront. 
Now, I've started to untar existing files with changed content and I'm wondering about the best way to invalidate cloudfront when that happens. Any ideas?

**Comment by sobotklp** [comment]
Generally, you shouldn't actively expire objects from Cloudfront. Your website visitors will probably have that content cached in their browser anyway, so they won't get the updates. 

The approach I've taken is to give different versions of your files version-specific URLs, so Cloudfront caches them separately. 

E.g. instead of /css/main.css, use /release-1.0.0/css/main.css

That will force returning clients to request the current version of the static assets.

untar-to-s3 supports adding the 'release-1.0.0' prefix to your files, but it can't help you with messing about with Cloudfront. If you really want to invalidate objects from Cloudfront, there is an API for that: http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Invalidation.html

**Comment by pessoa** [comment]
Maybe I can workaround this by dropping:
https://github.com/Kixeye/untar-to-s3/blob/master/untar-to-s3.py#L94
down to cloudfront minimum duration of 3600 seconds.

I see you have a TODO to allow control of this. Any ETA for that? :-)

**Comment by pessoa** [comment]
Nevermind this. I've found that cloudfront can be configured to "Forward Query Strings". So we have something like:
main.css?v=123 will force a request to the S3 origin if the previous version is main.css?v=122.

Thanks!
